In [4]:
import numpy as np

In [5]:
minha_lista = [1, 2, 3]

In [6]:
minha_lista

[1, 2, 3]

In [7]:
np.array(minha_lista) #Converte para um array de python

array([1, 2, 3])

In [8]:
minha_matriz = [[1,2,3], [4,5,6], [7,8,9]]

In [14]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(0, 10) #Cria uma sequencia de números

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [18]:
np.zeros(3) #Cria com 3 elementos zerados

array([0., 0., 0.])

In [19]:
np.zeros((5, 5)) #cria matriz de 5 por 5 zerada

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones(3)

array([1., 1., 1.])

In [21]:
np.eye(4) #Matriz identidade

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.linspace(0, 10, 2) #O 2 é números igualmente espaçados

array([ 0., 10.])

In [23]:
np.random.rand(5)

array([0.01792262, 0.43533786, 0.01140337, 0.68497752, 0.72552873])

In [24]:
np.random.rand(5) * 100

array([80.79032888, 38.35093543, 89.46311449, 18.32025913, 84.07029759])

In [25]:
np.random.rand(5, 4)

array([[0.59570967, 0.12512246, 0.07875994, 0.15122997],
       [0.16615352, 0.40604503, 0.16844571, 0.43386116],
       [0.8691772 , 0.81220607, 0.14476056, 0.05704219],
       [0.94489711, 0.06206196, 0.56141958, 0.91010619],
       [0.96257704, 0.03622106, 0.55020958, 0.49942668]])

In [27]:
np.random.rand(5, 3, 2)

array([[[0.07757787, 0.85983768],
        [0.62744446, 0.57395408],
        [0.31750604, 0.25274463]],

       [[0.0838531 , 0.13477516],
        [0.19294731, 0.70869309],
        [0.32872244, 0.39197916]],

       [[0.22382128, 0.46774195],
        [0.31671004, 0.68119282],
        [0.02154046, 0.06805252]],

       [[0.43169265, 0.87892968],
        [0.1497827 , 0.66487245],
        [0.54828512, 0.18687346]],

       [[0.86355554, 0.19293095],
        [0.5133925 , 0.78907389],
        [0.73457854, 0.60101968]]])

In [28]:
arr = np.random.rand(5)

In [29]:
arr

array([0.30190078, 0.5828293 , 0.71686977, 0.65112287, 0.00669003])

In [30]:
arr.max() #Encontra o maior valor do array

0.7168697675286185

In [31]:
arr.min()

0.006690027317160507